import type { Metadata } from "next";
import { Archivo} from "next/font/google";
import "./globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

const archivo= Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: "800",
})

export const metadata: Metadata = {
  title: "MaaSec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
